services:
  app:
    build: .
    container_name: lonch-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/builds:/tmp/builds
    depends_on:
      redis:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    container_name: lonch-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  redis:
    image: redis:8-alpine
    container_name: lonch-redis
    restart: unless-stopped
    volumes:
      - lonch_redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lonch_redis:
  caddy_data:
  caddy_config: