name: Deploy to GCP Compute Engine

on:
  push:
    branches: [ "dev", "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "$HOME/Lonch" ]; then
              git clone https://github.com/iCoderabhishek/Lonch.git $HOME/Lonch
            fi
            
            cd $HOME/Lonch
            git reset --hard HEAD
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            # export PATH="$HOME/.bun/bin:$PATH"
            # bun run docker
            docker-compose up -d --build
